#ifndef lint
static const char yysccsid[] = "@(#)yaccpar	1.9 (Berkeley) 02/21/93";
#endif

#include <stdlib.h>
#include <string.h>

#define YYBYACC 1
#define YYMAJOR 1
#define YYMINOR 9
#define YYPATCH 20070509

#define YYEMPTY (-1)
#define yyclearin    (yychar = YYEMPTY)
#define yyerrok      (yyerrflag = 0)
#define YYRECOVERING (yyerrflag != 0)

extern int yyparse(void);

static int yygrowstack(void);
#define YYPREFIX "yy"
#line 5 "cminor.y"
typedef union {
	struct decl *decl;
	struct stmt *stmt;
	struct expr *expr;
	struct type *type;
	struct param_list *param_list;
	char *name;
} YYSTYPE;
#line 78 "cminor.y"
#include "token.h"
#include <stdio.h>
#include "expr.h"
#include "stmt.h"
#include "param_list.h"
#include "decl.h"
#include "type.h"
#include "symbol.h"
#include "hash_table.h"
#include "scope.h"


/*
Manually declare the interface to the scanner generated by flex.
*/

extern char *yytext;
extern int yylex();
extern int yyerror(char *str);

struct decl * program = 0;
#line 54 "parser.tab.c"
#define TOKEN_ADD 257
#define TOKEN_SUBTRACT 258
#define TOKEN_MULT 259
#define TOKEN_DIV 260
#define TOKEN_MOD 261
#define TOKEN_ERROR 262
#define TOKEN_IDENT 263
#define TOKEN_STRING_LITERAL 264
#define TOKEN_INTEGER_LITERAL 265
#define TOKEN_CHARACTER_LITERAL 266
#define TOKEN_ARRAY 267
#define TOKEN_BOOLEAN 268
#define TOKEN_CHAR 269
#define TOKEN_ELSE 270
#define TOKEN_FALSE 271
#define TOKEN_FOR 272
#define TOKEN_FUNCTION 273
#define TOKEN_IF 274
#define TOKEN_INTEGER 275
#define TOKEN_PRINT 276
#define TOKEN_RETURN 277
#define TOKEN_STRING 278
#define TOKEN_TRUE 279
#define TOKEN_VOID 280
#define TOKEN_SUB 281
#define TOKEN_MUL 282
#define TOKEN_EXP 283
#define TOKEN_INCREMENT 284
#define TOKEN_DECREMENT 285
#define TOKEN_GT 286
#define TOKEN_GE 287
#define TOKEN_LT 288
#define TOKEN_LE 289
#define TOKEN_EQ 290
#define TOKEN_NE 291
#define TOKEN_ASSIGN 292
#define TOKEN_AND 293
#define TOKEN_OR 294
#define TOKEN_COLON 295
#define TOKEN_SEMICOLON 296
#define TOKEN_L_PAREN 297
#define TOKEN_R_PAREN 298
#define TOKEN_L_BRACE 299
#define TOKEN_R_BRACE 300
#define TOKEN_L_BRACKET 301
#define TOKEN_R_BRACKET 302
#define TOKEN_COMMA 303
#define TOKEN_LOGICAL_NOT 304
#define YYERRCODE 256
short yylhs[] = {                                        -1,
    0,    1,    1,    2,    2,    2,    2,    3,    3,    3,
    3,    3,    3,    3,    4,    4,    5,    5,    6,    8,
    8,    9,    9,   10,   10,   10,   10,   10,   10,   10,
   12,   11,   11,   11,   13,   13,   26,   26,   14,   14,
   15,   15,   15,   15,   15,   15,   15,   16,   16,   16,
   17,   17,   17,   17,   18,   18,   20,   20,   20,   19,
   19,   19,   25,   25,   25,   25,   21,   21,   21,   21,
   21,   21,   27,   22,   22,   23,   23,   28,   28,   28,
   24,   24,    7,
};
short yylen[] = {                                         2,
    1,    2,    0,    6,    4,    7,    8,    1,    1,    1,
    1,    5,    5,    1,    1,    0,    1,    3,    3,    2,
    0,    1,    1,    1,    2,    9,    1,    7,    3,    3,
    3,    5,    7,    9,    3,    1,    3,    1,    3,    1,
    3,    3,    3,    3,    3,    3,    1,    3,    3,    1,
    3,    3,    3,    1,    3,    1,    2,    2,    1,    2,
    2,    1,    4,    4,    3,    1,    1,    1,    1,    1,
    1,    1,    3,    1,    0,    1,    0,    3,    1,    1,
    1,    3,    1,
};
short yydefred[] = {                                      0,
   83,    0,    1,    0,    0,    2,    0,    0,   11,   10,
    0,    9,    8,   14,    0,    0,    0,    0,    5,   69,
   68,   70,   72,   71,    0,    0,    0,    0,   74,    0,
    0,    0,    0,    0,   59,   56,   66,    0,    0,    0,
    0,    0,    0,   57,    0,   58,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,   60,   61,    0,    0,    0,   15,    0,    0,
    0,    0,    0,    0,    0,   24,    0,    0,    0,   22,
   23,   27,    0,   80,    0,    0,    4,   65,    0,    0,
   76,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,   55,   12,   35,    0,   13,    0,
    0,    0,    0,    0,    0,    0,    0,    6,    0,   20,
    0,   25,    0,    0,    0,   63,   64,   18,   19,    0,
    0,   30,   29,   31,   73,   82,    0,   78,    7,    0,
    0,    0,   32,    0,    0,    0,    0,   28,   33,    0,
   26,   34,
};
short yydgoto[] = {                                       2,
    3,   76,   15,   67,   68,   69,   28,  116,   79,   80,
   81,   82,   29,   30,   31,   32,   33,   34,   35,   36,
   37,   38,   90,   84,   39,   40,   85,  117,
};
short yysindex[] = {                                   -238,
    0,    0,    0, -238, -275,    0, -151, -241,    0,    0,
 -151,    0,    0,    0, -273,  282, -235, -253,    0,    0,
    0,    0,    0,    0,  282,  282,  282, -243,    0, -224,
 -199, -248, -226, -216,    0,    0,    0, -225, -236, -255,
 -238,  239, -210,    0, -205,    0,  282,  282,  282,  282,
  282,  282,  282,  282,  282,  282,  282,  282,  282,  282,
  282, -151,    0,    0,  282,  282, -195,    0, -193, -183,
 -184, -182,  282,  282,  239,    0, -280, -186,  258,    0,
    0,    0, -244,    0, -178, -179,    0,    0, -177, -167,
    0, -164, -199, -248, -248, -248, -248, -248, -248, -226,
 -226, -216, -216, -216,    0,    0,    0, -224,    0, -238,
 -151,  282,  282, -156, -152, -150, -148,    0,  258,    0,
 -147,    0,  282, -200, -143,    0,    0,    0,    0, -128,
 -126,    0,    0,    0,    0,    0, -200,    0,    0,  282,
  258, -108,    0, -122,  282,  258, -106,    0,    0,  258,
    0,    0,
};
short yyrindex[] = {                                    170,
    0,    0,    0,  170,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0, -112,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0, -127,    0,  183,
 -157, -107,  118,    2,    0,    0,    0,    0,  -83, -228,
 -104, -103,    0,    0,    0,    0,  -97,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,  -96,    0,
    0,    0,  -84,  -82, -103,    0,  -36,    0, -103,    0,
    0,    0,  -78,    0,  -77,    0,    0,    0, -260,    0,
    0,    0,  -24,  -60,   45,  278,  301,  319,  337,  136,
  156,   25,   69,   92,    0,    0,    0,  349,    0,    0,
    0,  -82,    0,    0,    0,    0,    0,    0, -103,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,  -82,
    0,    0,    0,  197,  -80,    0,    0,    0,    0,    0,
    0,    0,
};
short yygindex[] = {                                      0,
  212,   94,   -9,    0,  125,    0,    1,  -38,   96, -119,
  -50,    0,  -18,  173,  192,  437,   27,   49,    0,  -11,
    0,  -67,  171,  -41,    0,    0,    0,  -39,
};
#define YYTABLESIZE 652
short yytable[] = {                                      43,
    5,   17,   86,   78,    5,   91,  115,   45,   56,    1,
   20,   21,   22,   44,    7,   46,   47,   23,   18,    7,
   48,  144,   19,   83,    1,   24,  148,   25,   89,   92,
  151,   91,   57,   58,   59,   81,   65,   81,   66,   81,
  120,   70,   77,   26,  130,   42,  107,   63,   64,  105,
   27,  122,  106,   47,   89,   60,   83,   48,  123,   16,
  121,   41,    1,   20,   21,   22,   61,   36,   49,   36,
   23,   36,  142,   36,   36,   77,   62,  147,   24,   77,
   25,  136,  100,  101,  138,   87,   50,   51,   52,   53,
   54,   55,   88,    4,  131,  149,   26,    4,  137,  152,
  121,  129,  109,   27,   89,   89,  102,  103,  104,  110,
   70,  111,  112,  118,  113,    8,    9,   10,   89,   77,
  125,   11,  121,   12,  124,  123,   13,  121,   14,   67,
  126,  121,   67,   67,   40,   40,   40,  127,   40,  132,
   40,   77,   40,  133,   40,   40,   77,  146,  122,  134,
   77,  135,  139,   67,   67,   67,   67,   67,   67,   67,
   67,   67,   67,   67,   67,   67,   67,  140,   67,    3,
   67,  141,   67,   62,   67,   67,   62,   62,   47,   47,
   47,   47,   47,   47,   47,   47,   47,  145,   47,   75,
   47,  150,   47,   16,   47,   47,   21,   62,   62,   62,
   77,   17,   62,   62,   62,   62,   62,   62,   62,   62,
   62,   77,   62,   75,   62,    6,   62,   75,   62,   62,
   67,   81,   79,   67,   67,   42,   42,   42,   42,   42,
   42,   42,   42,   42,  128,   42,  143,   42,  108,   42,
   93,   42,   42,  114,   67,   67,   67,   67,   67,   67,
   67,   67,   67,   67,   67,   67,   67,   67,   54,   67,
    0,   54,   54,   67,    0,    0,   67,   39,   39,   39,
    0,   39,    0,   39,    0,   39,    0,   39,   39,    0,
    0,   52,   54,   54,   52,   52,    0,   54,   54,   54,
   54,   54,   54,   54,   54,   54,    0,   54,    0,   54,
    0,   54,    0,   54,   54,   52,   52,    0,    0,    0,
   52,   52,   52,   52,   52,   52,   52,   52,   52,    0,
   52,    0,   52,    0,   52,   53,   52,   52,   53,   53,
   44,   44,   44,   44,   44,   44,   44,   44,   44,    0,
   44,    0,   44,    0,   44,    0,   44,   44,   51,   53,
   53,   51,   51,    0,   53,   53,   53,   53,   53,   53,
   53,   53,   53,    0,   53,    0,   53,    0,   53,    0,
   53,   53,   51,   51,   50,    0,    0,   51,   51,   51,
   51,   51,   51,   51,   51,   51,    0,   51,    0,   51,
    0,   51,   48,   51,   51,    0,    0,    0,   50,    0,
    0,    0,    0,   50,   50,   50,   50,   50,   50,   50,
   50,   50,   49,   50,    0,   50,   48,   50,    0,   50,
   50,   48,   48,   48,   48,   48,   48,   48,   48,   48,
    0,   48,    0,   48,    0,   48,   49,   48,   48,    0,
    0,   49,   49,   49,   49,   49,   49,   49,   49,   49,
    0,   49,    0,   49,    0,   49,    0,   49,   49,   22,
   22,   22,   22,    0,    0,    0,    0,   22,   22,    0,
   22,    0,   22,   22,   38,   22,   38,   22,   38,    0,
   38,    0,   38,    0,   38,   38,   94,   95,   96,   97,
   98,   99,    0,   22,    0,   22,   22,    0,    0,    0,
   22,    1,   20,   21,   22,    0,    0,    0,    0,   23,
   71,    0,   72,    0,   73,   74,    0,   24,    0,   25,
    1,   20,   21,   22,    0,    0,    0,    0,   23,   71,
    0,   72,    0,   73,   74,   26,   24,   75,   25,    0,
    0,    0,   27,    0,    1,   20,   21,   22,    0,    0,
    0,    0,   23,    0,   26,    0,  119,    0,    0,    0,
   24,   27,   25,   41,   41,   41,   41,   41,   41,   41,
   41,   41,    0,   41,    0,   41,    0,   41,   26,   41,
   41,    0,    0,    0,    0,   27,   43,   43,   43,   43,
   43,   43,   43,   43,   43,    0,   43,    0,   43,    0,
   43,    0,   43,   43,   45,   45,   45,   45,   45,   45,
   45,   45,   45,    0,   45,    0,   45,    0,   45,    0,
   45,   45,   46,   46,   46,   46,   46,   46,   46,   46,
   46,    0,   46,    0,   46,    0,   46,    0,   46,   46,
   37,    0,   37,    0,   37,    0,   37,    0,   37,    0,
   37,   37,
};
short yycheck[] = {                                      18,
    0,   11,   42,   42,    4,   47,   74,   26,  257,  263,
  264,  265,  266,   25,  295,   27,  297,  271,  292,  295,
  301,  141,  296,   42,  263,  279,  146,  281,   47,   48,
  150,   73,  281,  260,  261,  296,  292,  298,  294,  300,
   79,   41,   42,  297,  112,  299,   65,  284,  285,   61,
  304,  296,   62,  297,   73,  282,   75,  301,  303,  301,
   79,  297,  263,  264,  265,  266,  283,  296,  293,  298,
  271,  300,  140,  302,  303,   75,  302,  145,  279,   79,
  281,  123,   56,   57,  124,  296,  286,  287,  288,  289,
  290,  291,  298,    0,  113,  146,  297,    4,  299,  150,
  119,  111,  298,  304,  123,  124,   58,   59,   60,  303,
  110,  295,  297,  300,  297,  267,  268,  269,  137,  119,
  300,  273,  141,  275,  303,  303,  278,  146,  280,  257,
  298,  150,  260,  261,  292,  293,  294,  302,  296,  296,
  298,  141,  300,  296,  302,  303,  146,  270,  296,  300,
  150,  300,  296,  281,  282,  283,  284,  285,  286,  287,
  288,  289,  290,  291,  292,  293,  294,  296,  296,    0,
  298,  298,  300,  257,  302,  303,  260,  261,  286,  287,
  288,  289,  290,  291,  292,  293,  294,  296,  296,  302,
  298,  298,  300,  298,  302,  303,  300,  281,  282,  283,
  298,  298,  286,  287,  288,  289,  290,  291,  292,  293,
  294,  296,  296,  296,  298,    4,  300,  298,  302,  303,
  257,  300,  300,  260,  261,  286,  287,  288,  289,  290,
  291,  292,  293,  294,  110,  296,  141,  298,   66,  300,
   49,  302,  303,   73,  281,  282,  283,  284,  285,  286,
  287,  288,  289,  290,  291,  292,  293,  294,  257,  296,
   -1,  260,  261,  300,   -1,   -1,  303,  292,  293,  294,
   -1,  296,   -1,  298,   -1,  300,   -1,  302,  303,   -1,
   -1,  257,  281,  282,  260,  261,   -1,  286,  287,  288,
  289,  290,  291,  292,  293,  294,   -1,  296,   -1,  298,
   -1,  300,   -1,  302,  303,  281,  282,   -1,   -1,   -1,
  286,  287,  288,  289,  290,  291,  292,  293,  294,   -1,
  296,   -1,  298,   -1,  300,  257,  302,  303,  260,  261,
  286,  287,  288,  289,  290,  291,  292,  293,  294,   -1,
  296,   -1,  298,   -1,  300,   -1,  302,  303,  257,  281,
  282,  260,  261,   -1,  286,  287,  288,  289,  290,  291,
  292,  293,  294,   -1,  296,   -1,  298,   -1,  300,   -1,
  302,  303,  281,  282,  257,   -1,   -1,  286,  287,  288,
  289,  290,  291,  292,  293,  294,   -1,  296,   -1,  298,
   -1,  300,  257,  302,  303,   -1,   -1,   -1,  281,   -1,
   -1,   -1,   -1,  286,  287,  288,  289,  290,  291,  292,
  293,  294,  257,  296,   -1,  298,  281,  300,   -1,  302,
  303,  286,  287,  288,  289,  290,  291,  292,  293,  294,
   -1,  296,   -1,  298,   -1,  300,  281,  302,  303,   -1,
   -1,  286,  287,  288,  289,  290,  291,  292,  293,  294,
   -1,  296,   -1,  298,   -1,  300,   -1,  302,  303,  263,
  264,  265,  266,   -1,   -1,   -1,   -1,  271,  272,   -1,
  274,   -1,  276,  277,  292,  279,  294,  281,  296,   -1,
  298,   -1,  300,   -1,  302,  303,   50,   51,   52,   53,
   54,   55,   -1,  297,   -1,  299,  300,   -1,   -1,   -1,
  304,  263,  264,  265,  266,   -1,   -1,   -1,   -1,  271,
  272,   -1,  274,   -1,  276,  277,   -1,  279,   -1,  281,
  263,  264,  265,  266,   -1,   -1,   -1,   -1,  271,  272,
   -1,  274,   -1,  276,  277,  297,  279,  299,  281,   -1,
   -1,   -1,  304,   -1,  263,  264,  265,  266,   -1,   -1,
   -1,   -1,  271,   -1,  297,   -1,  299,   -1,   -1,   -1,
  279,  304,  281,  286,  287,  288,  289,  290,  291,  292,
  293,  294,   -1,  296,   -1,  298,   -1,  300,  297,  302,
  303,   -1,   -1,   -1,   -1,  304,  286,  287,  288,  289,
  290,  291,  292,  293,  294,   -1,  296,   -1,  298,   -1,
  300,   -1,  302,  303,  286,  287,  288,  289,  290,  291,
  292,  293,  294,   -1,  296,   -1,  298,   -1,  300,   -1,
  302,  303,  286,  287,  288,  289,  290,  291,  292,  293,
  294,   -1,  296,   -1,  298,   -1,  300,   -1,  302,  303,
  292,   -1,  294,   -1,  296,   -1,  298,   -1,  300,   -1,
  302,  303,
};
#define YYFINAL 2
#ifndef YYDEBUG
#define YYDEBUG 0
#endif
#define YYMAXTOKEN 304
#if YYDEBUG
char *yyname[] = {
"end-of-file",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"TOKEN_ADD","TOKEN_SUBTRACT",
"TOKEN_MULT","TOKEN_DIV","TOKEN_MOD","TOKEN_ERROR","TOKEN_IDENT",
"TOKEN_STRING_LITERAL","TOKEN_INTEGER_LITERAL","TOKEN_CHARACTER_LITERAL",
"TOKEN_ARRAY","TOKEN_BOOLEAN","TOKEN_CHAR","TOKEN_ELSE","TOKEN_FALSE",
"TOKEN_FOR","TOKEN_FUNCTION","TOKEN_IF","TOKEN_INTEGER","TOKEN_PRINT",
"TOKEN_RETURN","TOKEN_STRING","TOKEN_TRUE","TOKEN_VOID","TOKEN_SUB","TOKEN_MUL",
"TOKEN_EXP","TOKEN_INCREMENT","TOKEN_DECREMENT","TOKEN_GT","TOKEN_GE",
"TOKEN_LT","TOKEN_LE","TOKEN_EQ","TOKEN_NE","TOKEN_ASSIGN","TOKEN_AND",
"TOKEN_OR","TOKEN_COLON","TOKEN_SEMICOLON","TOKEN_L_PAREN","TOKEN_R_PAREN",
"TOKEN_L_BRACE","TOKEN_R_BRACE","TOKEN_L_BRACKET","TOKEN_R_BRACKET",
"TOKEN_COMMA","TOKEN_LOGICAL_NOT",
};
char *yyrule[] = {
"$accept : program",
"program : decl_list",
"decl_list : decl decl_list",
"decl_list :",
"decl : ident TOKEN_COLON type TOKEN_ASSIGN expr TOKEN_SEMICOLON",
"decl : ident TOKEN_COLON type TOKEN_SEMICOLON",
"decl : ident TOKEN_COLON type TOKEN_ASSIGN TOKEN_L_BRACE stmt_list TOKEN_R_BRACE",
"decl : ident TOKEN_COLON type TOKEN_ASSIGN TOKEN_L_BRACE expr_list_not_empty_b TOKEN_R_BRACE TOKEN_SEMICOLON",
"type : TOKEN_STRING",
"type : TOKEN_INTEGER",
"type : TOKEN_CHAR",
"type : TOKEN_BOOLEAN",
"type : TOKEN_ARRAY TOKEN_L_BRACKET opt_expr TOKEN_R_BRACKET type",
"type : TOKEN_FUNCTION type TOKEN_L_PAREN param_list TOKEN_R_PAREN",
"type : TOKEN_VOID",
"param_list : param_list_not_empty",
"param_list :",
"param_list_not_empty : param",
"param_list_not_empty : param TOKEN_COMMA param_list_not_empty",
"param : ident TOKEN_COLON type",
"stmt_list : stmt stmt_list",
"stmt_list :",
"stmt : stmt_matched",
"stmt : stmt_unmatched",
"stmt_matched : decl",
"stmt_matched : expr TOKEN_SEMICOLON",
"stmt_matched : TOKEN_FOR TOKEN_L_PAREN opt_expr TOKEN_SEMICOLON opt_expr TOKEN_SEMICOLON opt_expr TOKEN_R_PAREN stmt_matched",
"stmt_matched : stmt_block",
"stmt_matched : TOKEN_IF TOKEN_L_PAREN expr TOKEN_R_PAREN stmt_matched TOKEN_ELSE stmt_matched",
"stmt_matched : TOKEN_RETURN opt_expr TOKEN_SEMICOLON",
"stmt_matched : TOKEN_PRINT expr_list TOKEN_SEMICOLON",
"stmt_block : TOKEN_L_BRACE stmt_list TOKEN_R_BRACE",
"stmt_unmatched : TOKEN_IF TOKEN_L_PAREN expr TOKEN_R_PAREN stmt",
"stmt_unmatched : TOKEN_IF TOKEN_L_PAREN expr TOKEN_R_PAREN stmt_matched TOKEN_ELSE stmt_unmatched",
"stmt_unmatched : TOKEN_FOR TOKEN_L_PAREN opt_expr TOKEN_SEMICOLON opt_expr TOKEN_SEMICOLON opt_expr TOKEN_R_PAREN stmt_unmatched",
"expr : expr_no_assign TOKEN_ASSIGN expr",
"expr : expr_no_assign",
"expr_no_assign : expr_no_assign TOKEN_OR expr_no_or",
"expr_no_assign : expr_no_or",
"expr_no_or : expr_no_or TOKEN_AND expr_no_and",
"expr_no_or : expr_no_and",
"expr_no_and : expr_no_and TOKEN_LT expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_GT expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_LE expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_GE expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_EQ expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_NE expr_no_cmp",
"expr_no_and : expr_no_cmp",
"expr_no_cmp : expr_no_cmp TOKEN_ADD expr_no_arith",
"expr_no_cmp : expr_no_cmp TOKEN_SUB expr_no_arith",
"expr_no_cmp : expr_no_arith",
"expr_no_arith : expr_no_arith TOKEN_MUL expr_no_geo",
"expr_no_arith : expr_no_arith TOKEN_DIV expr_no_geo",
"expr_no_arith : expr_no_arith TOKEN_MOD expr_no_geo",
"expr_no_arith : expr_no_geo",
"expr_no_geo : expr_no_geo TOKEN_EXP expr_no_exp",
"expr_no_geo : expr_no_exp",
"expr_no_exp : TOKEN_SUB expr_no_exp",
"expr_no_exp : TOKEN_LOGICAL_NOT expr_no_exp",
"expr_no_exp : expr_no_unary",
"expr_no_unary : expr_group TOKEN_INCREMENT",
"expr_no_unary : expr_group TOKEN_DECREMENT",
"expr_no_unary : expr_group",
"expr_group : ident TOKEN_L_PAREN expr_list TOKEN_R_PAREN",
"expr_group : ident TOKEN_L_BRACKET expr TOKEN_R_BRACKET",
"expr_group : TOKEN_L_PAREN expr TOKEN_R_PAREN",
"expr_group : expr_primary",
"expr_primary : ident",
"expr_primary : TOKEN_INTEGER_LITERAL",
"expr_primary : TOKEN_STRING_LITERAL",
"expr_primary : TOKEN_CHARACTER_LITERAL",
"expr_primary : TOKEN_TRUE",
"expr_primary : TOKEN_FALSE",
"expr_block : TOKEN_L_BRACE expr_list_not_empty_b TOKEN_R_BRACE",
"opt_expr : expr",
"opt_expr :",
"expr_list : expr_list_not_empty",
"expr_list :",
"expr_list_not_empty_b : expr_block TOKEN_COMMA expr_list_not_empty_b",
"expr_list_not_empty_b : expr_block",
"expr_list_not_empty_b : expr_list_not_empty",
"expr_list_not_empty : expr",
"expr_list_not_empty : expr TOKEN_COMMA expr_list_not_empty",
"ident : TOKEN_IDENT",
};
#endif
#if YYDEBUG
#include <stdio.h>
#endif

/* define the initial stack-sizes */
#ifdef YYSTACKSIZE
#undef YYMAXDEPTH
#define YYMAXDEPTH  YYSTACKSIZE
#else
#ifdef YYMAXDEPTH
#define YYSTACKSIZE YYMAXDEPTH
#else
#define YYSTACKSIZE 10000
#define YYMAXDEPTH  10000
#endif
#endif

#define YYINITSTACKSIZE 500

int      yydebug;
int      yynerrs;
int      yyerrflag;
int      yychar;
short   *yyssp;
YYSTYPE *yyvsp;
YYSTYPE  yyval;
YYSTYPE  yylval;

/* variables for the parser stack */
static short   *yyss;
static short   *yysslim;
static YYSTYPE *yyvs;
static int      yystacksize;
#line 219 "cminor.y"

int yyerror(char *str)
{
	fprintf(stderr,"parse error: %s\n",str);
	return 0;
}
#line 479 "parser.tab.c"
/* allocate initial stack or double stack size, up to YYMAXDEPTH */
static int yygrowstack(void)
{
    int newsize, i;
    short *newss;
    YYSTYPE *newvs;

    if ((newsize = yystacksize) == 0)
        newsize = YYINITSTACKSIZE;
    else if (newsize >= YYMAXDEPTH)
        return -1;
    else if ((newsize *= 2) > YYMAXDEPTH)
        newsize = YYMAXDEPTH;

    i = yyssp - yyss;
    newss = (yyss != 0)
          ? (short *)realloc(yyss, newsize * sizeof(*newss))
          : (short *)malloc(newsize * sizeof(*newss));
    if (newss == 0)
        return -1;

    yyss  = newss;
    yyssp = newss + i;
    newvs = (yyvs != 0)
          ? (YYSTYPE *)realloc(yyvs, newsize * sizeof(*newvs))
          : (YYSTYPE *)malloc(newsize * sizeof(*newvs));
    if (newvs == 0)
        return -1;

    yyvs = newvs;
    yyvsp = newvs + i;
    yystacksize = newsize;
    yysslim = yyss + newsize - 1;
    return 0;
}

#define YYABORT goto yyabort
#define YYREJECT goto yyabort
#define YYACCEPT goto yyaccept
#define YYERROR goto yyerrlab
int
yyparse(void)
{
    register int yym, yyn, yystate;
#if YYDEBUG
    register const char *yys;

    if ((yys = getenv("YYDEBUG")) != 0)
    {
        yyn = *yys;
        if (yyn >= '0' && yyn <= '9')
            yydebug = yyn - '0';
    }
#endif

    yynerrs = 0;
    yyerrflag = 0;
    yychar = YYEMPTY;

    if (yyss == NULL && yygrowstack()) goto yyoverflow;
    yyssp = yyss;
    yyvsp = yyvs;
    *yyssp = yystate = 0;

yyloop:
    if ((yyn = yydefred[yystate]) != 0) goto yyreduce;
    if (yychar < 0)
    {
        if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, reading %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
    }
    if ((yyn = yysindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: state %d, shifting to state %d\n",
                    YYPREFIX, yystate, yytable[yyn]);
#endif
        if (yyssp >= yysslim && yygrowstack())
        {
            goto yyoverflow;
        }
        *++yyssp = yystate = yytable[yyn];
        *++yyvsp = yylval;
        yychar = YYEMPTY;
        if (yyerrflag > 0)  --yyerrflag;
        goto yyloop;
    }
    if ((yyn = yyrindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
        yyn = yytable[yyn];
        goto yyreduce;
    }
    if (yyerrflag) goto yyinrecovery;

    yyerror("syntax error");

#ifdef lint
    goto yyerrlab;
#endif

yyerrlab:
    ++yynerrs;

yyinrecovery:
    if (yyerrflag < 3)
    {
        yyerrflag = 3;
        for (;;)
        {
            if ((yyn = yysindex[*yyssp]) && (yyn += YYERRCODE) >= 0 &&
                    yyn <= YYTABLESIZE && yycheck[yyn] == YYERRCODE)
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: state %d, error recovery shifting\
 to state %d\n", YYPREFIX, *yyssp, yytable[yyn]);
#endif
                if (yyssp >= yysslim && yygrowstack())
                {
                    goto yyoverflow;
                }
                *++yyssp = yystate = yytable[yyn];
                *++yyvsp = yylval;
                goto yyloop;
            }
            else
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: error recovery discarding state %d\n",
                            YYPREFIX, *yyssp);
#endif
                if (yyssp <= yyss) goto yyabort;
                --yyssp;
                --yyvsp;
            }
        }
    }
    else
    {
        if (yychar == 0) goto yyabort;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
        yychar = YYEMPTY;
        goto yyloop;
    }

yyreduce:
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: state %d, reducing by rule %d (%s)\n",
                YYPREFIX, yystate, yyn, yyrule[yyn]);
#endif
    yym = yylen[yyn];
    if (yym)
        yyval = yyvsp[1-yym];
    else
        memset(&yyval, 0, sizeof yyval);
    switch (yyn)
    {
case 1:
#line 103 "cminor.y"
{program = yyvsp[0].decl;}
break;
case 2:
#line 105 "cminor.y"
{yyval.decl = yyvsp[-1].decl; yyvsp[-1].decl->next=yyvsp[0].decl;}
break;
case 3:
#line 106 "cminor.y"
{yyval.decl = 0;}
break;
case 4:
#line 108 "cminor.y"
{yyval.decl = decl_create(yyvsp[-5].name,yyvsp[-3].type,yyvsp[-1].expr,0,0);}
break;
case 5:
#line 109 "cminor.y"
{yyval.decl = decl_create(yyvsp[-3].name,yyvsp[-1].type,0,0,0);}
break;
case 6:
#line 110 "cminor.y"
{yyval.decl = decl_create(yyvsp[-6].name,yyvsp[-4].type,0,yyvsp[-1].stmt,0); if(!yyvsp[-1].stmt) {yyval.decl->code=stmt_create(STMT_EMPTY,0,0,0,0,0,0);};}
break;
case 7:
#line 111 "cminor.y"
{yyval.decl = decl_create(yyvsp[-7].name,yyvsp[-5].type,yyvsp[-2].expr,0,0);}
break;
case 8:
#line 113 "cminor.y"
{yyval.type = type_create(TYPE_STRING,0,0);}
break;
case 9:
#line 114 "cminor.y"
{yyval.type = type_create(TYPE_INTEGER,0,0);}
break;
case 10:
#line 115 "cminor.y"
{yyval.type = type_create(TYPE_CHARACTER,0,0);}
break;
case 11:
#line 116 "cminor.y"
{yyval.type = type_create(TYPE_BOOLEAN,0,0);}
break;
case 12:
#line 117 "cminor.y"
{yyval.type = type_create_array(TYPE_ARRAY,0,yyvsp[0].type,yyvsp[-2].expr);}
break;
case 13:
#line 118 "cminor.y"
{yyval.type = type_create(TYPE_FUNCTION,yyvsp[-1].param_list,yyvsp[-3].type);}
break;
case 14:
#line 119 "cminor.y"
{yyval.type = type_create(TYPE_VOID,0,0);}
break;
case 15:
#line 121 "cminor.y"
{yyval.param_list = yyvsp[0].param_list;}
break;
case 16:
#line 122 "cminor.y"
{yyval.param_list = 0;}
break;
case 17:
#line 124 "cminor.y"
{yyval.param_list = yyvsp[0].param_list;}
break;
case 18:
#line 125 "cminor.y"
{yyval.param_list = yyvsp[-2].param_list; yyvsp[-2].param_list->next = yyvsp[0].param_list;}
break;
case 19:
#line 127 "cminor.y"
{yyval.param_list = param_list_create(yyvsp[-2].name,yyvsp[0].type,0);}
break;
case 20:
#line 129 "cminor.y"
{yyval.stmt = yyvsp[-1].stmt; yyvsp[-1].stmt->next = yyvsp[0].stmt;}
break;
case 21:
#line 130 "cminor.y"
{yyval.stmt = 0;}
break;
case 22:
#line 132 "cminor.y"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 23:
#line 133 "cminor.y"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 24:
#line 135 "cminor.y"
{yyval.stmt = stmt_create(STMT_DECL,yyvsp[0].decl,0,0,0,0,0);}
break;
case 25:
#line 136 "cminor.y"
{yyval.stmt = stmt_create(STMT_EXPR,0,0,yyvsp[-1].expr,0,0,0);}
break;
case 26:
#line 137 "cminor.y"
{yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0);}
break;
case 27:
#line 138 "cminor.y"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 28:
#line 139 "cminor.y"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt);}
break;
case 29:
#line 140 "cminor.y"
{yyval.stmt = stmt_create(STMT_RETURN,0,0,yyvsp[-1].expr,0,0,0);}
break;
case 30:
#line 141 "cminor.y"
{yyval.stmt = stmt_create(STMT_PRINT,0,0,yyvsp[-1].expr,0,0,0);}
break;
case 31:
#line 143 "cminor.y"
{yyval.stmt = stmt_create(STMT_BLOCK,0,0,0,0,yyvsp[-1].stmt,0);}
break;
case 32:
#line 145 "cminor.y"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-2].expr,0,yyvsp[0].stmt,0);}
break;
case 33:
#line 146 "cminor.y"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt);}
break;
case 34:
#line 147 "cminor.y"
{yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0);}
break;
case 35:
#line 149 "cminor.y"
{yyval.expr = expr_create(EXPR_ASSIGN,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 36:
#line 150 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 37:
#line 151 "cminor.y"
{yyval.expr = expr_create(EXPR_OR,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 38:
#line 152 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 39:
#line 154 "cminor.y"
{yyval.expr = expr_create(EXPR_AND,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 40:
#line 155 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 41:
#line 157 "cminor.y"
{yyval.expr = expr_create(EXPR_LT,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 42:
#line 158 "cminor.y"
{yyval.expr = expr_create(EXPR_GT,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 43:
#line 159 "cminor.y"
{yyval.expr = expr_create(EXPR_LE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 44:
#line 160 "cminor.y"
{yyval.expr = expr_create(EXPR_GE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 45:
#line 161 "cminor.y"
{yyval.expr = expr_create(EXPR_EQ,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 46:
#line 162 "cminor.y"
{yyval.expr = expr_create(EXPR_NE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 47:
#line 163 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 48:
#line 165 "cminor.y"
{yyval.expr = expr_create(EXPR_ADD,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 49:
#line 166 "cminor.y"
{yyval.expr = expr_create(EXPR_SUB,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 50:
#line 167 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 51:
#line 169 "cminor.y"
{yyval.expr = expr_create(EXPR_MUL,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 52:
#line 170 "cminor.y"
{yyval.expr = expr_create(EXPR_DIV,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 53:
#line 171 "cminor.y"
{yyval.expr = expr_create(EXPR_MOD,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 54:
#line 172 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 55:
#line 174 "cminor.y"
{yyval.expr = expr_create(EXPR_EXP,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 56:
#line 175 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 57:
#line 177 "cminor.y"
{yyval.expr = expr_create(EXPR_NEG,0,yyvsp[0].expr);}
break;
case 58:
#line 178 "cminor.y"
{yyval.expr = expr_create(EXPR_NOT,0,yyvsp[0].expr);}
break;
case 59:
#line 179 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 60:
#line 181 "cminor.y"
{yyval.expr = expr_create(EXPR_INCR,yyvsp[-1].expr,0);}
break;
case 61:
#line 182 "cminor.y"
{yyval.expr = expr_create(EXPR_DECR,yyvsp[-1].expr,0);}
break;
case 62:
#line 183 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 63:
#line 185 "cminor.y"
{yyval.expr = expr_create(EXPR_FUNC,expr_create_name(yyvsp[-3].name),yyvsp[-1].expr);}
break;
case 64:
#line 186 "cminor.y"
{yyval.expr = expr_create(EXPR_ARRAY,expr_create_name(yyvsp[-3].name),yyvsp[-1].expr/*expr_create(EXPR_ARRAY_LIST,$3,$5)*/);}
break;
case 65:
#line 187 "cminor.y"
{yyval.expr = expr_create(EXPR_GROUP,yyvsp[-1].expr,0);}
break;
case 66:
#line 188 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 67:
#line 193 "cminor.y"
{yyval.expr = expr_create_name(yyvsp[0].name);}
break;
case 68:
#line 194 "cminor.y"
{yyval.expr = expr_create_integer_literal(atoi(yytext));}
break;
case 69:
#line 195 "cminor.y"
{char *buf; buf = strdup(yytext); yyval.expr = expr_create_string_literal(buf);}
break;
case 70:
#line 196 "cminor.y"
{yyval.expr = expr_create_character_literal(yytext[0]);}
break;
case 71:
#line 197 "cminor.y"
{yyval.expr = expr_create_boolean_literal(1);}
break;
case 72:
#line 198 "cminor.y"
{yyval.expr = expr_create_boolean_literal(0);}
break;
case 73:
#line 200 "cminor.y"
{yyval.expr = expr_create(EXPR_BLOCK,yyvsp[-1].expr,0);}
break;
case 74:
#line 202 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 75:
#line 203 "cminor.y"
{yyval.expr = 0;}
break;
case 76:
#line 205 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 77:
#line 206 "cminor.y"
{yyval.expr = 0;}
break;
case 78:
#line 208 "cminor.y"
{yyval.expr = expr_create(EXPR_BLOCK,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 79:
#line 209 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 80:
#line 210 "cminor.y"
{yyval.expr = expr_create(EXPR_BLOCK,yyvsp[0].expr,0);}
break;
case 81:
#line 212 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 82:
#line 213 "cminor.y"
{yyval.expr = expr_create(EXPR_LIST,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 83:
#line 215 "cminor.y"
{char *buf=0; buf = strdup(yytext); yyval.name = buf;}
break;
#line 992 "parser.tab.c"
    }
    yyssp -= yym;
    yystate = *yyssp;
    yyvsp -= yym;
    yym = yylhs[yyn];
    if (yystate == 0 && yym == 0)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", YYPREFIX, YYFINAL);
#endif
        yystate = YYFINAL;
        *++yyssp = YYFINAL;
        *++yyvsp = yyval;
        if (yychar < 0)
        {
            if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
            if (yydebug)
            {
                yys = 0;
                if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
                if (!yys) yys = "illegal-symbol";
                printf("%sdebug: state %d, reading %d (%s)\n",
                        YYPREFIX, YYFINAL, yychar, yys);
            }
#endif
        }
        if (yychar == 0) goto yyaccept;
        goto yyloop;
    }
    if ((yyn = yygindex[yym]) && (yyn += yystate) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yystate)
        yystate = yytable[yyn];
    else
        yystate = yydgoto[yym];
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: after reduction, shifting from state %d \
to state %d\n", YYPREFIX, *yyssp, yystate);
#endif
    if (yyssp >= yysslim && yygrowstack())
    {
        goto yyoverflow;
    }
    *++yyssp = yystate;
    *++yyvsp = yyval;
    goto yyloop;

yyoverflow:
    yyerror("yacc stack overflow");

yyabort:
    return (1);

yyaccept:
    return (0);
}
