#ifndef lint
static const char yysccsid[] = "@(#)yaccpar	1.9 (Berkeley) 02/21/93";
#endif

#include <stdlib.h>
#include <string.h>

#define YYBYACC 1
#define YYMAJOR 1
#define YYMINOR 9
#define YYPATCH 20070509

#define YYEMPTY (-1)
#define yyclearin    (yychar = YYEMPTY)
#define yyerrok      (yyerrflag = 0)
#define YYRECOVERING (yyerrflag != 0)

extern int yyparse(void);

static int yygrowstack(void);
#define YYPREFIX "yy"
#line 5 "cminor.y"
typedef union {
	struct decl *decl;
	struct stmt *stmt;
	struct expr *expr;
	struct type *type;
	struct param_list *param_list;
	char *name;
} YYSTYPE;
#line 78 "cminor.y"
#include "token.h"
#include <stdio.h>
#include "expr.h"
#include "stmt.h"
#include "param_list.h"
#include "decl.h"
#include "type.h"


/*
Manually declare the interface to the scanner generated by flex.
*/

extern char *yytext;
extern int yylex();
extern int yyerror(char *str);

struct decl * program = 0;
#line 51 "parser.tab.c"
#define TOKEN_ADD 257
#define TOKEN_SUBTRACT 258
#define TOKEN_MULT 259
#define TOKEN_DIV 260
#define TOKEN_MOD 261
#define TOKEN_ERROR 262
#define TOKEN_IDENT 263
#define TOKEN_STRING_LITERAL 264
#define TOKEN_INTEGER_LITERAL 265
#define TOKEN_CHARACTER_LITERAL 266
#define TOKEN_ARRAY 267
#define TOKEN_BOOLEAN 268
#define TOKEN_CHAR 269
#define TOKEN_ELSE 270
#define TOKEN_FALSE 271
#define TOKEN_FOR 272
#define TOKEN_FUNCTION 273
#define TOKEN_IF 274
#define TOKEN_INTEGER 275
#define TOKEN_PRINT 276
#define TOKEN_RETURN 277
#define TOKEN_STRING 278
#define TOKEN_TRUE 279
#define TOKEN_VOID 280
#define TOKEN_SUB 281
#define TOKEN_MUL 282
#define TOKEN_EXP 283
#define TOKEN_INCREMENT 284
#define TOKEN_DECREMENT 285
#define TOKEN_GT 286
#define TOKEN_GE 287
#define TOKEN_LT 288
#define TOKEN_LE 289
#define TOKEN_EQ 290
#define TOKEN_NE 291
#define TOKEN_ASSIGN 292
#define TOKEN_AND 293
#define TOKEN_OR 294
#define TOKEN_COLON 295
#define TOKEN_SEMICOLON 296
#define TOKEN_L_PAREN 297
#define TOKEN_R_PAREN 298
#define TOKEN_L_BRACE 299
#define TOKEN_R_BRACE 300
#define TOKEN_L_BRACKET 301
#define TOKEN_R_BRACKET 302
#define TOKEN_COMMA 303
#define TOKEN_LOGICAL_NOT 304
#define YYERRCODE 256
short yylhs[] = {                                        -1,
    0,    1,    1,    2,    2,    2,    2,    3,    3,    3,
    3,    3,    3,    3,    4,    4,    5,    5,    6,    8,
    8,    9,    9,   10,   10,   10,   10,   10,   10,   10,
   12,   11,   11,   11,   13,   13,   26,   26,   14,   14,
   15,   15,   15,   15,   15,   15,   15,   16,   16,   16,
   17,   17,   17,   17,   18,   18,   20,   20,   20,   19,
   19,   19,   25,   25,   25,   21,   21,   21,   21,   21,
   21,   21,   27,   22,   22,   23,   23,   28,   28,   28,
   24,   24,    7,
};
short yylen[] = {                                         2,
    1,    2,    0,    6,    4,    5,    8,    1,    1,    1,
    1,    5,    5,    1,    1,    0,    1,    3,    3,    2,
    0,    1,    1,    1,    2,    9,    1,    7,    3,    3,
    3,    5,    7,    9,    3,    1,    3,    1,    3,    1,
    3,    3,    3,    3,    3,    3,    1,    3,    3,    1,
    3,    3,    3,    1,    3,    1,    2,    2,    1,    2,
    2,    1,    4,    4,    1,    1,    1,    1,    1,    1,
    1,    3,    3,    1,    0,    1,    0,    3,    1,    1,
    1,    3,    1,
};
short yydefred[] = {                                      0,
   83,    0,    1,    0,    0,    2,    0,    0,   11,   10,
    0,    9,    8,   14,    0,    0,    0,    0,    5,   68,
   67,   69,   71,   70,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,   59,   56,   65,    0,    0,    0,
    0,    0,    6,    0,   57,    0,   58,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,   60,   61,    0,    0,   15,    0,
    0,    0,    0,    0,    0,    0,   24,    0,    0,    0,
   22,   23,   27,    0,   80,    0,    0,    4,   72,    0,
    0,   76,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,   55,   12,    0,   13,
    0,    0,    0,    0,    0,    0,    0,   31,    0,   20,
    0,   25,    0,    0,    0,   63,   64,   18,   19,    0,
    0,   30,   29,   73,   82,    0,   78,    7,    0,    0,
    0,   32,    0,    0,    0,    0,   28,   33,    0,   26,
   34,
};
short yydgoto[] = {                                       2,
    3,   77,   15,   68,   69,   70,   28,   79,   80,   81,
   82,   83,   29,   30,   31,   32,   33,   34,   35,   36,
   37,   38,   91,   85,   39,   40,   86,  117,
};
short yysindex[] = {                                   -259,
    0,    0,    0, -259, -286,    0, -189, -285,    0,    0,
 -189,    0,    0,    0, -209, -243, -279, -252,    0,    0,
    0,    0,    0,    0, -243, -243, -243, -199, -267, -261,
 -152, -247, -211, -235,    0,    0,    0, -262, -137, -237,
 -259,  235,    0, -192,    0, -226,    0, -243, -243, -243,
 -243, -243, -243, -243, -243, -243, -243, -243, -243, -243,
 -243, -243, -243, -189,    0,    0, -243, -238,    0, -229,
 -219, -205, -198, -243, -243,  235,    0, -232, -193,  254,
    0,    0,    0, -257,    0, -180, -186,    0,    0, -266,
 -170,    0, -251, -237, -152, -247, -247, -247, -247, -247,
 -247, -211, -211, -235, -235, -235,    0,    0, -261,    0,
 -259, -189, -243, -243, -166, -156, -157,    0,  254,    0,
 -179,    0, -243, -155, -151,    0,    0,    0,    0, -129,
 -225,    0,    0,    0,    0, -155,    0,    0, -243,  254,
 -127,    0,  -99, -243,  254, -111,    0,    0,  254,    0,
    0,
};
short yyrindex[] = {                                    189,
    0,    0,    0,  189,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0, -109,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0, -128, -208,  244,
  -28, -108,  114,   -2,    0,    0,    0,    0,  -84,  348,
 -107, -104,    0,    0,    0,    0,    0,  -98,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,  -97,
    0,    0,    0,  -85,  -83, -104,    0,  -40,    0, -104,
    0,    0,    0,  -67,    0,  -65,    0,    0,    0, -203,
    0,    0,    0,  357,  183,  -64,   41,  273,  291,  309,
  327,  132,  152,   21,   65,   88,    0,    0,  339,    0,
    0,    0,  -83,    0,    0,    0,    0,    0, -104,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,  -83,    0,
    0,    0,  193,  -61,    0,    0,    0,    0,    0,    0,
    0,
};
short yygindex[] = {                                      0,
  211,  115,   -9,    0,  120,    0,    1,  160,  117,  -81,
  -24,  243,  -18,  195,  216,  609,   93,  332,    0,  -10,
    0,  -69,  197,  -41,    0,  219,    0,  -39,
};
#define YYTABLESIZE 666
short yytable[] = {                                      44,
    5,   17,   87,    1,    5,  116,   92,   46,    7,   58,
    1,   20,   21,   22,   45,   16,   47,   41,   23,    1,
   20,   21,   22,   84,   50,   50,   24,   23,   25,   90,
   93,   51,   92,   59,   50,   24,  123,   25,  122,   64,
   50,   71,   78,  130,   26,  123,   42,   63,   60,   61,
  127,   27,  107,   26,  108,   90,   67,   84,  143,  110,
   27,  121,    7,  147,   48,   50,   50,  150,   49,  141,
   62,   89,  140,  111,  146,  112,   78,    8,    9,   10,
   78,  135,   18,   11,  137,   12,   19,   74,   13,   74,
   14,  113,   81,   74,   81,  131,   81,   48,  114,   50,
  121,   49,  129,   88,   90,   90,  118,    1,   20,   21,
   22,   71,   50,  125,    4,   23,  122,   90,    4,   78,
  148,  121,  124,   24,  151,   25,  121,  126,   66,  132,
  121,   66,   66,   52,   53,   54,   55,   56,   57,  133,
   78,   26,  134,  136,  138,   78,   65,   66,   27,   78,
  102,  103,   66,   66,   66,   66,   66,   66,   66,   66,
   66,   66,   66,   66,   66,   66,  139,   66,  144,   66,
  145,   66,   62,   66,   66,   62,   62,   47,   47,   47,
   47,   47,   47,   47,   47,   47,  149,   47,    3,   47,
   16,   47,   75,   47,   47,   21,   62,   62,   62,   77,
   17,   62,   62,   62,   62,   62,   62,   62,   62,   62,
   77,   62,   75,   62,    6,   62,   66,   62,   62,   66,
   66,   42,   42,   42,   42,   42,   42,   42,   42,   42,
  128,   42,   81,   42,   79,   42,   75,   42,   42,  120,
   66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
   66,   66,   66,   66,   54,   66,  142,   54,   54,   66,
   43,  109,   66,   40,   40,   40,   95,   40,   94,   40,
  115,   40,    0,   40,   40,    0,    0,   52,   54,   54,
   52,   52,    0,   54,   54,   54,   54,   54,   54,   54,
   54,   54,    0,   54,    0,   54,    0,   54,    0,   54,
   54,   52,   52,    0,    0,    0,   52,   52,   52,   52,
   52,   52,   52,   52,   52,    0,   52,    0,   52,    0,
   52,   53,   52,   52,   53,   53,   44,   44,   44,   44,
   44,   44,   44,   44,   44,    0,   44,    0,   44,    0,
   44,    0,   44,   44,   51,   53,   53,   51,   51,    0,
   53,   53,   53,   53,   53,   53,   53,   53,   53,    0,
   53,    0,   53,    0,   53,    0,   53,   53,   51,   51,
   50,    0,    0,   51,   51,   51,   51,   51,   51,   51,
   51,   51,    0,   51,    0,   51,    0,   51,   48,   51,
   51,  104,  105,  106,   50,    0,    0,    0,    0,   50,
   50,   50,   50,   50,   50,   50,   50,   50,   49,   50,
    0,   50,   48,   50,    0,   50,   50,   48,   48,   48,
   48,   48,   48,   48,   48,   48,    0,   48,    0,   48,
    0,   48,   49,   48,   48,    0,    0,   49,   49,   49,
   49,   49,   49,   49,   49,   49,    0,   49,    0,   49,
    0,   49,    0,   49,   49,   22,   22,   22,   22,    0,
    0,    0,    0,   22,   22,    0,   22,    0,   22,   22,
    0,   22,    0,   22,   39,   39,   39,    0,   39,    0,
   39,    0,   39,    0,   39,   39,    0,    0,    0,   22,
    0,   22,   22,    0,    0,    0,   22,    1,   20,   21,
   22,    0,    0,    0,    0,   23,   72,    0,   73,    0,
   74,   75,    0,   24,    0,   25,    1,   20,   21,   22,
    0,    0,    0,    0,   23,   72,    0,   73,    0,   74,
   75,   26,   24,   76,   25,   38,    0,   38,   27,   38,
    0,   38,    0,   38,    0,   38,   38,    0,    0,    0,
   26,    0,  119,    0,    0,    0,    0,   27,   41,   41,
   41,   41,   41,   41,   41,   41,   41,    0,   41,    0,
   41,    0,   41,    0,   41,   41,   43,   43,   43,   43,
   43,   43,   43,   43,   43,    0,   43,    0,   43,    0,
   43,    0,   43,   43,   45,   45,   45,   45,   45,   45,
   45,   45,   45,    0,   45,    0,   45,    0,   45,    0,
   45,   45,   46,   46,   46,   46,   46,   46,   46,   46,
   46,    0,   46,    0,   46,    0,   46,    0,   46,   46,
   37,    0,   37,    0,   37,    0,   37,    0,   37,   36,
   37,   37,    0,   36,    0,   36,    0,   36,   35,   36,
   36,    0,   35,    0,   35,    0,   35,    0,   35,   35,
   96,   97,   98,   99,  100,  101,
};
short yycheck[] = {                                      18,
    0,   11,   42,  263,    4,   75,   48,   26,  295,  257,
  263,  264,  265,  266,   25,  301,   27,  297,  271,  263,
  264,  265,  266,   42,  292,  292,  279,  271,  281,   48,
   49,  293,   74,  281,  292,  279,  303,  281,  296,  302,
  292,   41,   42,  113,  297,  303,  299,  283,  260,  261,
  302,  304,   63,  297,   64,   74,  294,   76,  140,  298,
  304,   80,  295,  145,  297,  292,  292,  149,  301,  139,
  282,  298,  298,  303,  144,  295,   76,  267,  268,  269,
   80,  123,  292,  273,  124,  275,  296,  296,  278,  298,
  280,  297,  296,  302,  298,  114,  300,  297,  297,  292,
  119,  301,  112,  296,  123,  124,  300,  263,  264,  265,
  266,  111,  292,  300,    0,  271,  296,  136,    4,  119,
  145,  140,  303,  279,  149,  281,  145,  298,  257,  296,
  149,  260,  261,  286,  287,  288,  289,  290,  291,  296,
  140,  297,  300,  299,  296,  145,  284,  285,  304,  149,
   58,   59,  281,  282,  283,  284,  285,  286,  287,  288,
  289,  290,  291,  292,  293,  294,  296,  296,  296,  298,
  270,  300,  257,  302,  303,  260,  261,  286,  287,  288,
  289,  290,  291,  292,  293,  294,  298,  296,    0,  298,
  298,  300,  302,  302,  303,  300,  281,  282,  283,  298,
  298,  286,  287,  288,  289,  290,  291,  292,  293,  294,
  296,  296,  296,  298,    4,  300,  257,  302,  303,  260,
  261,  286,  287,  288,  289,  290,  291,  292,  293,  294,
  111,  296,  300,  298,  300,  300,  298,  302,  303,   80,
  281,  282,  283,  284,  285,  286,  287,  288,  289,  290,
  291,  292,  293,  294,  257,  296,  140,  260,  261,  300,
   18,   67,  303,  292,  293,  294,   51,  296,   50,  298,
   74,  300,   -1,  302,  303,   -1,   -1,  257,  281,  282,
  260,  261,   -1,  286,  287,  288,  289,  290,  291,  292,
  293,  294,   -1,  296,   -1,  298,   -1,  300,   -1,  302,
  303,  281,  282,   -1,   -1,   -1,  286,  287,  288,  289,
  290,  291,  292,  293,  294,   -1,  296,   -1,  298,   -1,
  300,  257,  302,  303,  260,  261,  286,  287,  288,  289,
  290,  291,  292,  293,  294,   -1,  296,   -1,  298,   -1,
  300,   -1,  302,  303,  257,  281,  282,  260,  261,   -1,
  286,  287,  288,  289,  290,  291,  292,  293,  294,   -1,
  296,   -1,  298,   -1,  300,   -1,  302,  303,  281,  282,
  257,   -1,   -1,  286,  287,  288,  289,  290,  291,  292,
  293,  294,   -1,  296,   -1,  298,   -1,  300,  257,  302,
  303,   60,   61,   62,  281,   -1,   -1,   -1,   -1,  286,
  287,  288,  289,  290,  291,  292,  293,  294,  257,  296,
   -1,  298,  281,  300,   -1,  302,  303,  286,  287,  288,
  289,  290,  291,  292,  293,  294,   -1,  296,   -1,  298,
   -1,  300,  281,  302,  303,   -1,   -1,  286,  287,  288,
  289,  290,  291,  292,  293,  294,   -1,  296,   -1,  298,
   -1,  300,   -1,  302,  303,  263,  264,  265,  266,   -1,
   -1,   -1,   -1,  271,  272,   -1,  274,   -1,  276,  277,
   -1,  279,   -1,  281,  292,  293,  294,   -1,  296,   -1,
  298,   -1,  300,   -1,  302,  303,   -1,   -1,   -1,  297,
   -1,  299,  300,   -1,   -1,   -1,  304,  263,  264,  265,
  266,   -1,   -1,   -1,   -1,  271,  272,   -1,  274,   -1,
  276,  277,   -1,  279,   -1,  281,  263,  264,  265,  266,
   -1,   -1,   -1,   -1,  271,  272,   -1,  274,   -1,  276,
  277,  297,  279,  299,  281,  292,   -1,  294,  304,  296,
   -1,  298,   -1,  300,   -1,  302,  303,   -1,   -1,   -1,
  297,   -1,  299,   -1,   -1,   -1,   -1,  304,  286,  287,
  288,  289,  290,  291,  292,  293,  294,   -1,  296,   -1,
  298,   -1,  300,   -1,  302,  303,  286,  287,  288,  289,
  290,  291,  292,  293,  294,   -1,  296,   -1,  298,   -1,
  300,   -1,  302,  303,  286,  287,  288,  289,  290,  291,
  292,  293,  294,   -1,  296,   -1,  298,   -1,  300,   -1,
  302,  303,  286,  287,  288,  289,  290,  291,  292,  293,
  294,   -1,  296,   -1,  298,   -1,  300,   -1,  302,  303,
  292,   -1,  294,   -1,  296,   -1,  298,   -1,  300,  292,
  302,  303,   -1,  296,   -1,  298,   -1,  300,  292,  302,
  303,   -1,  296,   -1,  298,   -1,  300,   -1,  302,  303,
   52,   53,   54,   55,   56,   57,
};
#define YYFINAL 2
#ifndef YYDEBUG
#define YYDEBUG 0
#endif
#define YYMAXTOKEN 304
#if YYDEBUG
char *yyname[] = {
"end-of-file",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"TOKEN_ADD","TOKEN_SUBTRACT",
"TOKEN_MULT","TOKEN_DIV","TOKEN_MOD","TOKEN_ERROR","TOKEN_IDENT",
"TOKEN_STRING_LITERAL","TOKEN_INTEGER_LITERAL","TOKEN_CHARACTER_LITERAL",
"TOKEN_ARRAY","TOKEN_BOOLEAN","TOKEN_CHAR","TOKEN_ELSE","TOKEN_FALSE",
"TOKEN_FOR","TOKEN_FUNCTION","TOKEN_IF","TOKEN_INTEGER","TOKEN_PRINT",
"TOKEN_RETURN","TOKEN_STRING","TOKEN_TRUE","TOKEN_VOID","TOKEN_SUB","TOKEN_MUL",
"TOKEN_EXP","TOKEN_INCREMENT","TOKEN_DECREMENT","TOKEN_GT","TOKEN_GE",
"TOKEN_LT","TOKEN_LE","TOKEN_EQ","TOKEN_NE","TOKEN_ASSIGN","TOKEN_AND",
"TOKEN_OR","TOKEN_COLON","TOKEN_SEMICOLON","TOKEN_L_PAREN","TOKEN_R_PAREN",
"TOKEN_L_BRACE","TOKEN_R_BRACE","TOKEN_L_BRACKET","TOKEN_R_BRACKET",
"TOKEN_COMMA","TOKEN_LOGICAL_NOT",
};
char *yyrule[] = {
"$accept : program",
"program : decl_list",
"decl_list : decl decl_list",
"decl_list :",
"decl : ident TOKEN_COLON type TOKEN_ASSIGN expr TOKEN_SEMICOLON",
"decl : ident TOKEN_COLON type TOKEN_SEMICOLON",
"decl : ident TOKEN_COLON type TOKEN_ASSIGN stmt_block",
"decl : ident TOKEN_COLON type TOKEN_ASSIGN TOKEN_L_BRACE expr_list_not_empty_b TOKEN_R_BRACE TOKEN_SEMICOLON",
"type : TOKEN_STRING",
"type : TOKEN_INTEGER",
"type : TOKEN_CHAR",
"type : TOKEN_BOOLEAN",
"type : TOKEN_ARRAY TOKEN_L_BRACKET opt_expr TOKEN_R_BRACKET type",
"type : TOKEN_FUNCTION type TOKEN_L_PAREN param_list TOKEN_R_PAREN",
"type : TOKEN_VOID",
"param_list : param_list_not_empty",
"param_list :",
"param_list_not_empty : param",
"param_list_not_empty : param TOKEN_COMMA param_list_not_empty",
"param : ident TOKEN_COLON type",
"stmt_list : stmt stmt_list",
"stmt_list :",
"stmt : stmt_matched",
"stmt : stmt_unmatched",
"stmt_matched : decl",
"stmt_matched : expr TOKEN_SEMICOLON",
"stmt_matched : TOKEN_FOR TOKEN_L_PAREN opt_expr TOKEN_SEMICOLON opt_expr TOKEN_SEMICOLON opt_expr TOKEN_R_PAREN stmt_matched",
"stmt_matched : stmt_block",
"stmt_matched : TOKEN_IF TOKEN_L_PAREN expr TOKEN_R_PAREN stmt_matched TOKEN_ELSE stmt_matched",
"stmt_matched : TOKEN_RETURN opt_expr TOKEN_SEMICOLON",
"stmt_matched : TOKEN_PRINT expr_list TOKEN_SEMICOLON",
"stmt_block : TOKEN_L_BRACE stmt_list TOKEN_R_BRACE",
"stmt_unmatched : TOKEN_IF TOKEN_L_PAREN expr TOKEN_R_PAREN stmt",
"stmt_unmatched : TOKEN_IF TOKEN_L_PAREN expr TOKEN_R_PAREN stmt_matched TOKEN_ELSE stmt_unmatched",
"stmt_unmatched : TOKEN_FOR TOKEN_L_PAREN opt_expr TOKEN_SEMICOLON opt_expr TOKEN_SEMICOLON opt_expr TOKEN_R_PAREN stmt_unmatched",
"expr : expr TOKEN_ASSIGN expr_no_assign",
"expr : expr_no_assign",
"expr_no_assign : expr_no_assign TOKEN_OR expr_no_or",
"expr_no_assign : expr_no_or",
"expr_no_or : expr_no_or TOKEN_AND expr_no_and",
"expr_no_or : expr_no_and",
"expr_no_and : expr_no_and TOKEN_LT expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_GT expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_LE expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_GE expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_EQ expr_no_cmp",
"expr_no_and : expr_no_and TOKEN_NE expr_no_cmp",
"expr_no_and : expr_no_cmp",
"expr_no_cmp : expr_no_cmp TOKEN_ADD expr_no_arith",
"expr_no_cmp : expr_no_cmp TOKEN_SUB expr_no_arith",
"expr_no_cmp : expr_no_arith",
"expr_no_arith : expr_no_arith TOKEN_MUL expr_no_geo",
"expr_no_arith : expr_no_arith TOKEN_DIV expr_no_geo",
"expr_no_arith : expr_no_arith TOKEN_MOD expr_no_geo",
"expr_no_arith : expr_no_geo",
"expr_no_geo : expr_no_geo TOKEN_EXP expr_no_exp",
"expr_no_geo : expr_no_exp",
"expr_no_exp : TOKEN_SUB expr_no_exp",
"expr_no_exp : TOKEN_LOGICAL_NOT expr_no_exp",
"expr_no_exp : expr_no_unary",
"expr_no_unary : expr_group TOKEN_INCREMENT",
"expr_no_unary : expr_group TOKEN_DECREMENT",
"expr_no_unary : expr_group",
"expr_group : ident TOKEN_L_PAREN expr_list TOKEN_R_PAREN",
"expr_group : ident TOKEN_L_BRACKET expr TOKEN_R_BRACKET",
"expr_group : expr_primary",
"expr_primary : ident",
"expr_primary : TOKEN_INTEGER_LITERAL",
"expr_primary : TOKEN_STRING_LITERAL",
"expr_primary : TOKEN_CHARACTER_LITERAL",
"expr_primary : TOKEN_TRUE",
"expr_primary : TOKEN_FALSE",
"expr_primary : TOKEN_L_PAREN expr TOKEN_R_PAREN",
"expr_block : TOKEN_L_BRACE expr_list_not_empty_b TOKEN_R_BRACE",
"opt_expr : expr",
"opt_expr :",
"expr_list : expr_list_not_empty",
"expr_list :",
"expr_list_not_empty_b : expr_block TOKEN_COMMA expr_list_not_empty_b",
"expr_list_not_empty_b : expr_block",
"expr_list_not_empty_b : expr_list_not_empty",
"expr_list_not_empty : expr",
"expr_list_not_empty : expr TOKEN_COMMA expr_list_not_empty",
"ident : TOKEN_IDENT",
};
#endif
#if YYDEBUG
#include <stdio.h>
#endif

/* define the initial stack-sizes */
#ifdef YYSTACKSIZE
#undef YYMAXDEPTH
#define YYMAXDEPTH  YYSTACKSIZE
#else
#ifdef YYMAXDEPTH
#define YYSTACKSIZE YYMAXDEPTH
#else
#define YYSTACKSIZE 10000
#define YYMAXDEPTH  10000
#endif
#endif

#define YYINITSTACKSIZE 500

int      yydebug;
int      yynerrs;
int      yyerrflag;
int      yychar;
short   *yyssp;
YYSTYPE *yyvsp;
YYSTYPE  yyval;
YYSTYPE  yylval;

/* variables for the parser stack */
static short   *yyss;
static short   *yysslim;
static YYSTYPE *yyvs;
static int      yystacksize;
#line 213 "cminor.y"

int yyerror(char *str)
{
	fprintf(stderr,"parse error: %s\n",str);
	return 0;
}
#line 478 "parser.tab.c"
/* allocate initial stack or double stack size, up to YYMAXDEPTH */
static int yygrowstack(void)
{
    int newsize, i;
    short *newss;
    YYSTYPE *newvs;

    if ((newsize = yystacksize) == 0)
        newsize = YYINITSTACKSIZE;
    else if (newsize >= YYMAXDEPTH)
        return -1;
    else if ((newsize *= 2) > YYMAXDEPTH)
        newsize = YYMAXDEPTH;

    i = yyssp - yyss;
    newss = (yyss != 0)
          ? (short *)realloc(yyss, newsize * sizeof(*newss))
          : (short *)malloc(newsize * sizeof(*newss));
    if (newss == 0)
        return -1;

    yyss  = newss;
    yyssp = newss + i;
    newvs = (yyvs != 0)
          ? (YYSTYPE *)realloc(yyvs, newsize * sizeof(*newvs))
          : (YYSTYPE *)malloc(newsize * sizeof(*newvs));
    if (newvs == 0)
        return -1;

    yyvs = newvs;
    yyvsp = newvs + i;
    yystacksize = newsize;
    yysslim = yyss + newsize - 1;
    return 0;
}

#define YYABORT goto yyabort
#define YYREJECT goto yyabort
#define YYACCEPT goto yyaccept
#define YYERROR goto yyerrlab
int
yyparse(void)
{
    register int yym, yyn, yystate;
#if YYDEBUG
    register const char *yys;

    if ((yys = getenv("YYDEBUG")) != 0)
    {
        yyn = *yys;
        if (yyn >= '0' && yyn <= '9')
            yydebug = yyn - '0';
    }
#endif

    yynerrs = 0;
    yyerrflag = 0;
    yychar = YYEMPTY;

    if (yyss == NULL && yygrowstack()) goto yyoverflow;
    yyssp = yyss;
    yyvsp = yyvs;
    *yyssp = yystate = 0;

yyloop:
    if ((yyn = yydefred[yystate]) != 0) goto yyreduce;
    if (yychar < 0)
    {
        if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, reading %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
    }
    if ((yyn = yysindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: state %d, shifting to state %d\n",
                    YYPREFIX, yystate, yytable[yyn]);
#endif
        if (yyssp >= yysslim && yygrowstack())
        {
            goto yyoverflow;
        }
        *++yyssp = yystate = yytable[yyn];
        *++yyvsp = yylval;
        yychar = YYEMPTY;
        if (yyerrflag > 0)  --yyerrflag;
        goto yyloop;
    }
    if ((yyn = yyrindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
        yyn = yytable[yyn];
        goto yyreduce;
    }
    if (yyerrflag) goto yyinrecovery;

    yyerror("syntax error");

#ifdef lint
    goto yyerrlab;
#endif

yyerrlab:
    ++yynerrs;

yyinrecovery:
    if (yyerrflag < 3)
    {
        yyerrflag = 3;
        for (;;)
        {
            if ((yyn = yysindex[*yyssp]) && (yyn += YYERRCODE) >= 0 &&
                    yyn <= YYTABLESIZE && yycheck[yyn] == YYERRCODE)
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: state %d, error recovery shifting\
 to state %d\n", YYPREFIX, *yyssp, yytable[yyn]);
#endif
                if (yyssp >= yysslim && yygrowstack())
                {
                    goto yyoverflow;
                }
                *++yyssp = yystate = yytable[yyn];
                *++yyvsp = yylval;
                goto yyloop;
            }
            else
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: error recovery discarding state %d\n",
                            YYPREFIX, *yyssp);
#endif
                if (yyssp <= yyss) goto yyabort;
                --yyssp;
                --yyvsp;
            }
        }
    }
    else
    {
        if (yychar == 0) goto yyabort;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
        yychar = YYEMPTY;
        goto yyloop;
    }

yyreduce:
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: state %d, reducing by rule %d (%s)\n",
                YYPREFIX, yystate, yyn, yyrule[yyn]);
#endif
    yym = yylen[yyn];
    if (yym)
        yyval = yyvsp[1-yym];
    else
        memset(&yyval, 0, sizeof yyval);
    switch (yyn)
    {
case 1:
#line 100 "cminor.y"
{program = yyvsp[0].decl;}
break;
case 2:
#line 102 "cminor.y"
{yyval.decl = yyvsp[-1].decl; yyvsp[-1].decl->next=yyvsp[0].decl;}
break;
case 3:
#line 103 "cminor.y"
{yyval.decl = 0;}
break;
case 4:
#line 105 "cminor.y"
{yyval.decl = decl_create(yyvsp[-5].name,yyvsp[-3].type,yyvsp[-1].expr,0,0);}
break;
case 5:
#line 106 "cminor.y"
{yyval.decl = decl_create(yyvsp[-3].name,yyvsp[-1].type,0,0,0);}
break;
case 6:
#line 107 "cminor.y"
{yyval.decl = decl_create(yyvsp[-4].name,yyvsp[-2].type,0,yyvsp[0].stmt,0);}
break;
case 7:
#line 108 "cminor.y"
{yyval.decl = decl_create(yyvsp[-7].name,yyvsp[-5].type,yyvsp[-2].expr,0,0);}
break;
case 8:
#line 110 "cminor.y"
{yyval.type = type_create(TYPE_STRING,0,0);}
break;
case 9:
#line 111 "cminor.y"
{yyval.type = type_create(TYPE_INTEGER,0,0);}
break;
case 10:
#line 112 "cminor.y"
{yyval.type = type_create(TYPE_CHARACTER,0,0);}
break;
case 11:
#line 113 "cminor.y"
{yyval.type = type_create(TYPE_BOOLEAN,0,0);}
break;
case 12:
#line 114 "cminor.y"
{yyval.type = type_create_array(TYPE_ARRAY,0,yyvsp[0].type,yyvsp[-2].expr);}
break;
case 13:
#line 115 "cminor.y"
{yyval.type = type_create(TYPE_FUNCTION,yyvsp[-1].param_list,yyvsp[-3].type);}
break;
case 14:
#line 116 "cminor.y"
{yyval.type = type_create(TYPE_VOID,0,0);}
break;
case 15:
#line 118 "cminor.y"
{yyval.param_list = yyvsp[0].param_list;}
break;
case 16:
#line 119 "cminor.y"
{yyval.param_list = 0;}
break;
case 17:
#line 121 "cminor.y"
{yyval.param_list = yyvsp[0].param_list;}
break;
case 18:
#line 122 "cminor.y"
{yyval.param_list = yyvsp[-2].param_list; yyvsp[-2].param_list->next = yyvsp[0].param_list;}
break;
case 19:
#line 124 "cminor.y"
{yyval.param_list = param_list_create(yyvsp[-2].name,yyvsp[0].type,0);}
break;
case 20:
#line 126 "cminor.y"
{yyval.stmt = yyvsp[-1].stmt; yyvsp[-1].stmt->next = yyvsp[0].stmt;}
break;
case 21:
#line 127 "cminor.y"
{yyval.stmt = 0;}
break;
case 22:
#line 129 "cminor.y"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 23:
#line 130 "cminor.y"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 24:
#line 132 "cminor.y"
{yyval.stmt = stmt_create(STMT_DECL,yyvsp[0].decl,0,0,0,0,0);}
break;
case 25:
#line 133 "cminor.y"
{yyval.stmt = stmt_create(STMT_EXPR,0,0,yyvsp[-1].expr,0,0,0);}
break;
case 26:
#line 134 "cminor.y"
{yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0);}
break;
case 27:
#line 135 "cminor.y"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 28:
#line 136 "cminor.y"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt);}
break;
case 29:
#line 137 "cminor.y"
{yyval.stmt = stmt_create(STMT_RETURN,0,0,yyvsp[-1].expr,0,0,0);}
break;
case 30:
#line 138 "cminor.y"
{yyval.stmt = stmt_create(STMT_PRINT,0,0,yyvsp[-1].expr,0,0,0);}
break;
case 31:
#line 140 "cminor.y"
{yyval.stmt = stmt_create(STMT_BLOCK,0,0,0,0,yyvsp[-1].stmt,0);}
break;
case 32:
#line 142 "cminor.y"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-2].expr,0,yyvsp[0].stmt,0);}
break;
case 33:
#line 143 "cminor.y"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt);}
break;
case 34:
#line 144 "cminor.y"
{yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0);}
break;
case 35:
#line 146 "cminor.y"
{yyval.expr = expr_create(EXPR_ASSIGN,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 36:
#line 147 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 37:
#line 148 "cminor.y"
{yyval.expr = expr_create(EXPR_OR,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 38:
#line 149 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 39:
#line 151 "cminor.y"
{yyval.expr = expr_create(EXPR_AND,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 40:
#line 152 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 41:
#line 154 "cminor.y"
{yyval.expr = expr_create(EXPR_LT,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 42:
#line 155 "cminor.y"
{yyval.expr = expr_create(EXPR_GT,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 43:
#line 156 "cminor.y"
{yyval.expr = expr_create(EXPR_LE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 44:
#line 157 "cminor.y"
{yyval.expr = expr_create(EXPR_GE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 45:
#line 158 "cminor.y"
{yyval.expr = expr_create(EXPR_EQ,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 46:
#line 159 "cminor.y"
{yyval.expr = expr_create(EXPR_NE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 47:
#line 160 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 48:
#line 162 "cminor.y"
{yyval.expr = expr_create(EXPR_ADD,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 49:
#line 163 "cminor.y"
{yyval.expr = expr_create(EXPR_SUB,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 50:
#line 164 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 51:
#line 166 "cminor.y"
{yyval.expr = expr_create(EXPR_MUL,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 52:
#line 167 "cminor.y"
{yyval.expr = expr_create(EXPR_DIV,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 53:
#line 168 "cminor.y"
{yyval.expr = expr_create(EXPR_MOD,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 54:
#line 169 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 55:
#line 171 "cminor.y"
{yyval.expr = expr_create(EXPR_EXP,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 56:
#line 172 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 57:
#line 174 "cminor.y"
{yyval.expr = expr_create(EXPR_NEG,0,yyvsp[0].expr);}
break;
case 58:
#line 175 "cminor.y"
{yyval.expr = expr_create(EXPR_NOT,0,yyvsp[0].expr);}
break;
case 59:
#line 176 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 60:
#line 178 "cminor.y"
{yyval.expr = expr_create(EXPR_INCR,yyvsp[-1].expr,0);}
break;
case 61:
#line 179 "cminor.y"
{yyval.expr = expr_create(EXPR_DECR,yyvsp[-1].expr,0);}
break;
case 62:
#line 180 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 63:
#line 182 "cminor.y"
{yyval.expr = expr_create(EXPR_FUNC,expr_create_name(yyvsp[-3].name),yyvsp[-1].expr);}
break;
case 64:
#line 183 "cminor.y"
{yyval.expr = expr_create(EXPR_ARRAY,expr_create_name(yyvsp[-3].name),yyvsp[-1].expr);}
break;
case 65:
#line 184 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 66:
#line 186 "cminor.y"
{yyval.expr = expr_create_name(yyvsp[0].name);}
break;
case 67:
#line 187 "cminor.y"
{yyval.expr = expr_create_integer_literal(atoi(yytext));}
break;
case 68:
#line 188 "cminor.y"
{char *buf; buf = strcpy(malloc(strnlen(yytext,256)+1),yytext); yyval.expr = expr_create_string_literal(buf);}
break;
case 69:
#line 189 "cminor.y"
{yyval.expr = expr_create_character_literal(yytext[0]);}
break;
case 70:
#line 190 "cminor.y"
{yyval.expr = expr_create_boolean_literal(1);}
break;
case 71:
#line 191 "cminor.y"
{yyval.expr = expr_create_boolean_literal(0);}
break;
case 72:
#line 192 "cminor.y"
{yyval.expr = expr_create(EXPR_GROUP,yyvsp[-1].expr,0);}
break;
case 73:
#line 194 "cminor.y"
{yyval.expr = expr_create(EXPR_BLOCK,yyvsp[-1].expr,0);}
break;
case 74:
#line 196 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 75:
#line 197 "cminor.y"
{yyval.expr = 0;}
break;
case 76:
#line 199 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 77:
#line 200 "cminor.y"
{yyval.expr = 0;}
break;
case 78:
#line 202 "cminor.y"
{yyval.expr = expr_create(EXPR_BLOCK,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 79:
#line 203 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 80:
#line 204 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 81:
#line 206 "cminor.y"
{yyval.expr = yyvsp[0].expr;}
break;
case 82:
#line 207 "cminor.y"
{yyval.expr = expr_create(EXPR_LIST,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 83:
#line 209 "cminor.y"
{char *buf=0; buf = strdup(yytext); yyval.name = buf;}
break;
#line 991 "parser.tab.c"
    }
    yyssp -= yym;
    yystate = *yyssp;
    yyvsp -= yym;
    yym = yylhs[yyn];
    if (yystate == 0 && yym == 0)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", YYPREFIX, YYFINAL);
#endif
        yystate = YYFINAL;
        *++yyssp = YYFINAL;
        *++yyvsp = yyval;
        if (yychar < 0)
        {
            if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
            if (yydebug)
            {
                yys = 0;
                if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
                if (!yys) yys = "illegal-symbol";
                printf("%sdebug: state %d, reading %d (%s)\n",
                        YYPREFIX, YYFINAL, yychar, yys);
            }
#endif
        }
        if (yychar == 0) goto yyaccept;
        goto yyloop;
    }
    if ((yyn = yygindex[yym]) && (yyn += yystate) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yystate)
        yystate = yytable[yyn];
    else
        yystate = yydgoto[yym];
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: after reduction, shifting from state %d \
to state %d\n", YYPREFIX, *yyssp, yystate);
#endif
    if (yyssp >= yysslim && yygrowstack())
    {
        goto yyoverflow;
    }
    *++yyssp = yystate;
    *++yyvsp = yyval;
    goto yyloop;

yyoverflow:
    yyerror("yacc stack overflow");

yyabort:
    return (1);

yyaccept:
    return (0);
}
